### PR TITLE
Path completion support

### PR DESCRIPTION
**Pull request by khud**
It is initial support of path completion capabilities for arbitrary string literals. This completion supports Unix like systems and Windows in uniform way, only paths with normal slashes will be completed. For Windows both styles are supported: `c:/Program Files` and `/Program Files`. Unfortunately dynamic changes of working directory by `setwd()` aren't supported in this PR, but I am working it on.

### CODE REVIEW

**Comment by holgerbrandl** [comment]
sorry for the late reply. It's a great idea to have path-completion support. Let me know once you think that the PR for testing & merging.

**Comment by khud** [comment]
I have tested PR on Mac OS 10.11.6, Windows 10 and Ubuntu MATE 16.04. Works pretty good. Let's try yourself, I believe it is ready for merge.

**Comment by holgerbrandl** [comment]
Awesome, I have look asap.

**Comment by holgerbrandl** [comment]
I took the liberty to change the completion logic a bit to also take the script file into account, and to resolve relative paths such as "./". See above commit for details. Next we would need to provide `setwd` support I guess.

The updated plugin was published as v1.0..9 to the plugin repo (which usually takes another day to get reviewed by jb).

**Comment by khud** [comment]
Nice work, thank you! I will provide `setwd` support soon.

**Comment by holgerbrandl** [comment]
I still wonder how we could add unit test support for the completion provider?  Not just for path completion but in general. @ktisha ?

**Pull request merged**
