### PR TITLE
Changed Color themes according to Default or Darcula

### PR DESCRIPTION
**Pull request by hkmoon**
Changed Color themes according to Default or Darcula

Still I am trying to figure out how to highlight function and variable, however, someday we need to redesign BNF rules. ;)

### CODE REVIEW

**Comment by jewellsean** [comment]
Is there support for custom function and variable highlighting? 

I only see these types highlighted: 

screen shot 2018-09-25 at 13 14 53

I just discovered this package and am very excited to switch from RStudio.

**Comment by holgerbrandl** [comment]
Not yet, but at least variable highlighting should be easy to do by patching com.r4intellij.highlighting.RSyntaxHighlighterColors

I think, there's no easy way to distinguish custom from library functions on the highlighter level.

**Comment by jewellsean** [comment]
Thanks for the response! 

By patching, I assume that you mean adding a ```TextAttributesKey``` [here](https://github.com/holgerbrandl/r4intellij/blob/master/src/com/r4intellij/highlighting/RSyntaxHighlighterColors.java)? Is there a good location to look for all possible ``R_* `` values? 

> I think, there's no easy way to distinguish custom from library functions on the highlighter level.

I don't see any function highlighting. Am I missing an option? 

I can see that there may be some use cases to highlight custom and library functions, but for my purposes any function highlighting would be great. 

Thanks!

**Comment by holgerbrandl** [comment]
The colors are bound to the lexer in com.r4intellij.highlighting.RSyntaxHighlighter

Just coloring function calls might be tricky because of the way call expressions are defined in `r.bnf`
```
call_expression ::= expression argument_list
```
`expression` can be a almost anything here (see the grammar spec)

Custom function calls would  be lexed to something like `primitive_expression argument_list` but just when actually resolving reference we know the type (variable of custom function definition) of each `primitive_expression`. 

So in order to highlight function calls we would somehow need to use resolver information for highlighting. I'm not sure if this is possible with the platform API ( @ktisha ?).

**Comment by jewellsean** [comment]
Thanks for your response. 

I may try to patch in order to get variable highlighting.

**Pull request merged**
