### PR TITLE
This PR resolves some bugs of not showing color editorbox

### PR DESCRIPTION
**Pull request by hkmoon**
This PR changed RGrammar for having EOL in the expression.
Additionally, ColorEditorbox problem is resolved.

### CODE REVIEW

**Comment by holgerbrandl** [comment]
The PR is not applicable, but it's maybe not so clear and mainly my fault: I've used the approach
http://stackoverflow.com/questions/2763006/change-the-current-branch-to-master-in-git
to make the v0.9 branch the new master without actually merging into it. See the (messy == sorry) revision tree for details.

I've now learned how to locally work with pull requests without merging them in right away. See https://gist.github.com/piscisaureus/3342247
for this useful approach.

I've cherry picked some of your grammar modifications and this fixed
https://github.com/holgerbrandl/r4intellij/issues/18

Concerning the other grammar changes: I don't think that they are 100% correct
1) %>% is not a token (or all the others are as well)

2) It's not clear why operators are handled differently in the PR
    '-' expr |
    '+' expr_or_assign |

3) role of "PINP expr |" is not clear because PINP seems refer back to %in% which just and arith_misc operator.

4) r.flex: "in" is a keyword (without the quotes)
http://cran.r-project.org/doc/manuals/r-release/R-lang.html#Reserved-words
thus 
  "in" { return R_IN; }
was correct and it's broken in the PR

In think in the long run the parser-def needs to reflect 
http://cran.r-project.org/doc/manuals/r-release/R-lang.html
better. I've started this process by filing 
https://github.com/holgerbrandl/r4intellij/issues/41

The current master 0273cd0b7d3fc52ac0131d2a5eebad507527ae36 already contains a single-line parser unit test (testDcastFormula). 

I fear function that call highlighting needs to be delayed a bit (even if I like the idea) until the parser becomes more stable again.

Thanks for the help!

**Comment by hkmoon** [comment]
> 1) %>% is not a token (or all the others are as well)
For me, those are tokens otherwise we will end up with " > requires <expr>" rather than ">%".
expr <- a %>% b %>% c
PIPEs are needed to be handled as token.

> 2) It's not clear why operators are handled differently in the PR
> '-' expr |
> '+' expr_or_assign |
because ggplot uses + as an concatenator not as an operator. In this case, this rule is able to evaluate ggplot scheme.

> 3) role of "PINP expr |" is not clear because PINP seems refer back to %in% which just and arith_misc operator.
We need to separate ARITH_MISC for the contexts. a %in% b is a kind of expression which is very different than others. For example, "a %in% b" can be used as a function argument, however, others do not look similar behaviors like the others'.

> 4) r.flex: "in" is a keyword (without the quotes)
> http://cran.r-project.org/doc/manuals/r-release/R-lang.html#Reserved-words
> thus
> "in" { return R_IN; }
If we do not use "%in%" as a token, the parser would consider "%in%" as the wrong expression of "in" rule. That is why I consider ARITH_MISC as token.

Feel free to discuss all the use cases for our new BNF parser.

**Comment by hkmoon** [comment]
> I've now learned how to locally work with pull requests without merging them in right away. See https://gist.github.com/piscisaureus/3342247
> for this useful approach.

This is truly useful, isn't it? We do not have to contaminate our tree by merging. Just cherry-pick great stuffs from others' repositories. This makes evolution mechanism of source code eco-system. ;)

**Comment by holgerbrandl** [comment]
Indeed, I was very excited as well when I discovered it.

**Comment by hkmoon** [comment]
> I fear function that call highlighting needs to be delayed a bit (even if I like the idea) until the parser becomes more stable again.

I totally understand your fear. ;) Because readability was more important at that time, I spent some time to fix the parser (even if it's super unstable now) for understanding function annotation. Let's move it on slowly. However, I am sure r4intellij will be awesome in the end.

**Comment by holgerbrandl** [comment]
I love your comments about my parser comments. This is really the type of
discussion which will push the project forward. I've no time today to work
through them, but I'll come back to you once I've did some research.

> However, I am sure r4intellij will be awesome in the end.
It is already: I've just downloaded a recent copy of RStudio and it does
not detect syntax errors AT ALL, so my guess is that they do simple lexing.
So imho r4i is already the superior product. :-)

I've just pushed out the fix for the EOF as v0.9.1 into the plugin
repository.

My plan for the rest of the week is to compile a post for my blog, which
I'll subsequently register to RBloggers. This will definitely help to get
the necessary attention and more users. Maybe even some new contributors...
;-)

**Comment by holgerbrandl** [comment]
The parser has been entirely replaced, so I'd think that this PR is no longer valid.

**Pull request closed without merging**
